DIM: 32
SEED: 55
BATCH_SIZE: 64
GPU_DEVICE: 1
BENCHMARK: 'Mix3toMix10'
MAX_ITER: 5001
LR: 0.001
INNER_ITERS: 15
MEAN_LOWER: -0.05
MEAN_UPPER: 0.05
emb_method: 'transformer'
D_HYPERPARAMS:
  # ICNN & MLP
  in_dim: 32
  hidden_layer_sizes:
    - 64
    - 128
    - 128
    - 64
  # ICNN only
  rank: 1
  strong_convexity: 0.0001
  dropout: 0.00
  activation: celu
h_hyperparams:
  uncond_in_size: 0
  cond_in_size: 2
  layers:
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
  num_cond_embs: 1
COND_IN_SIZE: 128