DIM: 64
SEED: 0
BATCH_SIZE: 256
GPU_DEVICE: 1
BENCHMARK: 'Mix3toMix10'
MAX_ITER: 5001
LR: 0.001
INNER_ITERS: 20
D_HYPERPARAMS:
  # ICNN & MLP
  dim: 64
  hidden_layer_sizes:
    - 64
    - 64
    - 32
  # ICNN only
  rank: 1
  strong_convexity: 0.0001
  # dropout: 0.01
  activation: celu
COND_IN_SIZE: 32